---
- name: Prepare Python virtual environment
  pip:
    state: present
    name: "{{ python_packages }}"
    virtualenv: "{{ source_path }}"
    virtualenv_command: "python3.9 -m venv"
  become: yes
  become_user: "{{ service_user }}"

- name: Enable working uWSGI binary in home directory of an user
  block:
    - name: Set SELinux file context mapping definitions of uWSGI binary
      sefcontext:
        target: "{{ source_path }}/bin/uwsgi"
        setype: bin_t
        state: present

    - name: Set SELinux security context of uWSGI binary
      file:
        path: "{{ source_path }}/bin/uwsgi"
        setype: bin_t
        seuser: system_u

- name: Prepare uwsgi.ini
  template:
    dest: "{{ source_path }}/src/backend/uwsgi.ini"
    src: uwsgi.ini.j2
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: 0600
    force: yes

- name: Prepare started script of backend service
  template:
    dest: "/usr/local/bin/mirror_service_backend.sh"
    src: mirror_service_backend.sh.j2
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: 0755
    force: yes

- name: Install systemd service of uWSGI backend
  template:
    dest: "/etc/systemd/system/mirror_service_backend.service"
    src: mirror_service_backend.service.j2
    group: "{{ service_user }}"
    owner: "{{ service_user }}"
    mode: 0640
    force: 'yes'

- name: Enable systemd service of uWSGI backend
  systemd:
    name: mirror_service_backend.service
    state: restarted
    enabled: yes
    masked: no
    daemon_reload: yes
