---
- name: Update local repo with mirrors list
  git:
    repo: "https://github.com/AlmaLinux/mirrors.git"
    dest: "{{ config_root }}/mirrors/updates"
    clone: yes
    update: yes
    accept_hostkey: yes
