---

- name: Ansible preparation
  block:
    - include_tasks: ansible_preparation.yml
  tags:
    - ansible

- name: Main tasks
  block:
    - name: Deploy tasks
      block:
        - include_tasks: common_setup.yml
        - include_tasks: deploy_files.yml
        - include_tasks: get_mirrors_repo.yml
        - include_tasks: create_dbs_systemd_timer.yml
        - include_tasks: create_mirrors_systemd_timer.yml
        - include_tasks: redis_configuration.yml
        - include_tasks: backend_installation.yml
        - include_tasks: nginx_configuration.yml
      tags:
        - deploy

    - name: Tests
      block:
        - include_tasks: tests.yml
      tags:
        - tests
  vars:
    ansible_python_interpreter: "/usr/bin/python3.6"
