---
- name: Enable persistent storage for Redis
  lineinfile:
    path: /etc/redis.conf
    regexp: '^appendonly no$'
    line: 'appendonly yes'
    state: present
    insertbefore: BOF

- name: Enable redis socket
  lineinfile:
    path: /etc/redis.conf
    regexp: '^unixsocket'
    line: unixsocket /var/run/redis/redis.sock
    state: present
    insertbefore: BOF

- name: Set redis socket perms
  lineinfile:
    path: /etc/redis.conf
    regex: '^unixsocketperm'
    line: unixsocketperm 777
    state: present
    insertbefore: BOF

- name: Start Redis
  systemd:
    enabled: yes
    masked: no
    state: started
    name: redis
